/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CourseCourseIdIndexRouteImport } from './routes/course/$courseId/index'
import { Route as CourseCourseIdSyllabusRouteImport } from './routes/course/$courseId/syllabus'
import { Route as CourseCourseIdAssignmentAssignmentIdRouteImport } from './routes/course/$courseId/assignment/$assignmentId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdIndexRoute = CourseCourseIdIndexRouteImport.update({
  id: '/course/$courseId/',
  path: '/course/$courseId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdSyllabusRoute = CourseCourseIdSyllabusRouteImport.update({
  id: '/course/$courseId/syllabus',
  path: '/course/$courseId/syllabus',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdAssignmentAssignmentIdRoute =
  CourseCourseIdAssignmentAssignmentIdRouteImport.update({
    id: '/course/$courseId/assignment/$assignmentId',
    path: '/course/$courseId/assignment/$assignmentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/course/$courseId/syllabus': typeof CourseCourseIdSyllabusRoute
  '/course/$courseId': typeof CourseCourseIdIndexRoute
  '/course/$courseId/assignment/$assignmentId': typeof CourseCourseIdAssignmentAssignmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/course/$courseId/syllabus': typeof CourseCourseIdSyllabusRoute
  '/course/$courseId': typeof CourseCourseIdIndexRoute
  '/course/$courseId/assignment/$assignmentId': typeof CourseCourseIdAssignmentAssignmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/course/$courseId/syllabus': typeof CourseCourseIdSyllabusRoute
  '/course/$courseId/': typeof CourseCourseIdIndexRoute
  '/course/$courseId/assignment/$assignmentId': typeof CourseCourseIdAssignmentAssignmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/course/$courseId/syllabus'
    | '/course/$courseId'
    | '/course/$courseId/assignment/$assignmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/course/$courseId/syllabus'
    | '/course/$courseId'
    | '/course/$courseId/assignment/$assignmentId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/course/$courseId/syllabus'
    | '/course/$courseId/'
    | '/course/$courseId/assignment/$assignmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  CourseCourseIdSyllabusRoute: typeof CourseCourseIdSyllabusRoute
  CourseCourseIdIndexRoute: typeof CourseCourseIdIndexRoute
  CourseCourseIdAssignmentAssignmentIdRoute: typeof CourseCourseIdAssignmentAssignmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId/': {
      id: '/course/$courseId/'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof CourseCourseIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId/syllabus': {
      id: '/course/$courseId/syllabus'
      path: '/course/$courseId/syllabus'
      fullPath: '/course/$courseId/syllabus'
      preLoaderRoute: typeof CourseCourseIdSyllabusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId/assignment/$assignmentId': {
      id: '/course/$courseId/assignment/$assignmentId'
      path: '/course/$courseId/assignment/$assignmentId'
      fullPath: '/course/$courseId/assignment/$assignmentId'
      preLoaderRoute: typeof CourseCourseIdAssignmentAssignmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  CourseCourseIdSyllabusRoute: CourseCourseIdSyllabusRoute,
  CourseCourseIdIndexRoute: CourseCourseIdIndexRoute,
  CourseCourseIdAssignmentAssignmentIdRoute:
    CourseCourseIdAssignmentAssignmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
